version: "3"

services:
  postgres:   
    image: "postgres"   
    container_name: "server"   
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=db_name      
    ports:
      - "54320:5432"